/**
 * Inbound email parsing: normalize Resend's `email.received` payload into the
 * fields the ingest path needs, and strip quoted reply history so the ingested
 * message is just what the visitor actually wrote.
 */
import { describe, it, expect } from 'vitest'
import type { ConversationId } from '@quackback/ids'
import {
  parseInboundEmail,
  parseRawEmail,
  extractReplyText,
  extractEmailAddress,
  parseMessageIdList,
  messageIdDomain,
  isAutoGeneratedEmail,
  mailLoopSignal,
  decodeEncodedWords,
  normalizeSenderAddress,
  inboundDedupeKey,
  MAX_DEDUPE_KEY_CHARS,
  MAX_TRANSPORT_MESSAGE_ID_CHARS,
  type ParsedInboundEmail,
} from '../conversation.email-inbound'
// The real address grammar, so the loop guard's fixtures are minted and read by
// the same code the running system uses. A stand-in predicate here would pass
// against a guard wired to nothing.
import { inboundReplyToAddress, isOwnInboundAddress } from '../conversation.email-channel'

describe('parseInboundEmail', () => {
  it('normalizes an array `to`, reads `from`/`subject`/`text`, and the Message-ID header', () => {
    const parsed = parseInboundEmail({
      to: ['reply+conversation_abc@tenaevexeo.resend.app'],
      from: 'Jane Visitor <jane@example.com>',
      subject: 'Re: Your ticket',
      text: 'Thanks, that worked!',
      headers: [
        { name: 'Message-ID', value: '<msg-123@mail.example.com>' },
        { name: 'X-Other', value: 'ignored' },
      ],
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc@tenaevexeo.resend.app'])
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.subject).toBe('Re: Your ticket')
    expect(parsed.text).toBe('Thanks, that worked!')
    expect(parsed.messageId).toBe('<msg-123@mail.example.com>')
  })

  it('accepts a string `to` and an object-shaped headers map (case-insensitive)', () => {
    const parsed = parseInboundEmail({
      to: 'reply+conversation_xyz@tenaevexeo.resend.app',
      from: 'bob@example.com',
      headers: { 'message-id': '<abc@x>' },
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_xyz@tenaevexeo.resend.app'])
    expect(parsed.messageId).toBe('<abc@x>')
  })

  it('reads Reply-To from the header, or from the payload field when the header is absent', () => {
    // Both spellings occur: a provider that hands us the raw header block, and
    // one that lifts Reply-To into a field of its own. The loop guard's only
    // evidence lives here, so a front door that dropped it would quietly stop
    // recognising our own mail.
    expect(
      parseInboundEmail({
        to: 'support@tenaevexeo.resend.app',
        headers: [{ name: 'Reply-To', value: 'Acme <ws-t1+cabc.sig@tenaevexeo.resend.app>' }],
      }).replyToAddresses
    ).toEqual(['Acme <ws-t1+cabc.sig@tenaevexeo.resend.app>'])
    expect(
      parseInboundEmail({ to: 'support@tenaevexeo.resend.app', reply_to: 'ops@acme.example' })
        .replyToAddresses
    ).toEqual(['ops@acme.example'])
    expect(parseInboundEmail({ to: 'support@tenaevexeo.resend.app' }).replyToAddresses).toEqual([])
  })

  it('reads the payload field in the ARRAY shape a lifted address list arrives in', () => {
    // A payload that lifts Reply-To out of the header block carries an address
    // LIST, and a list is an array. `to` and `cc` beside it have always been read
    // that way; a Reply-To reader that only understood a bare string answered
    // "no Reply-To at all" for the exact payload shape it was written for, and
    // the loop guard downstream has no other evidence to fall back on.
    expect(
      parseInboundEmail({ to: 'support@tenaevexeo.resend.app', reply_to: ['ops@acme.example'] })
        .replyToAddresses
    ).toEqual(['ops@acme.example'])
    expect(
      parseInboundEmail({ to: 'support@tenaevexeo.resend.app', replyTo: ['ops@acme.example'] })
        .replyToAddresses
    ).toEqual(['ops@acme.example'])
    expect(
      parseInboundEmail({
        to: 'support@tenaevexeo.resend.app',
        reply_to: ['Acme <ws-t1+cabc.sig@tenaevexeo.resend.app>', 'ops@acme.example'],
      }).replyToAddresses
    ).toEqual(['Acme <ws-t1+cabc.sig@tenaevexeo.resend.app>', 'ops@acme.example'])
  })

  it('reads EVERY Reply-To header, and reads the same ones the raw front door does', () => {
    // RFC 5322 permits one Reply-To, so a message with two is malformed and no
    // reading of it is more correct than another. What is not optional is that
    // the two front doors give the SAME answer: a guard whose verdict depends on
    // which door a message came through is a guard with a second, undocumented
    // rule. Both read all of them, which is also the reading that cannot be
    // evaded by prepending a decoy.
    const ours = 'Acme <ws-t1+cabc.sig@tenaevexeo.resend.app>'
    const headers = [
      { name: 'Reply-To', value: 'Decoy <decoy@example.com>' },
      { name: 'Reply-To', value: ours },
    ]
    const webhook = parseInboundEmail({ to: 'support@tenaevexeo.resend.app', headers })
    const rawDoor = parseRawEmail(
      [
        'To: support@tenaevexeo.resend.app',
        'Reply-To: Decoy <decoy@example.com>',
        `Reply-To: ${ours}`,
        '',
        'body',
      ].join('\r\n')
    )
    expect(webhook.replyToAddresses).toEqual(['Decoy <decoy@example.com>', ours])
    expect(webhook.replyToAddresses).toEqual(rawDoor.replyToAddresses)
  })

  it('falls back to the top-level email id when no Message-ID header is present', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      from: 'a@b.com',
      email_id: 'email_fallback_1',
    })
    expect(parsed.messageId).toBe('email_fallback_1')
  })

  it('captures the provider email id, and message_id outranks it for dedupe (#320)', () => {
    const withBoth = parseInboundEmail({
      to: ['x@y.com'],
      from: 'a@b.com',
      email_id: 'em_1',
      message_id: '<mid@provider>',
    })
    expect(withBoth.messageId).toBe('<mid@provider>')
    expect(withBoth.emailId).toBe('em_1')

    // A Message-ID header still wins for dedupe; emailId is unaffected by it.
    const withHeader = parseInboundEmail({
      to: ['x@y.com'],
      headers: [{ name: 'Message-ID', value: '<hdr@mail>' }],
      email_id: 'em_2',
    })
    expect(withHeader.messageId).toBe('<hdr@mail>')
    expect(withHeader.emailId).toBe('em_2')
  })

  it('returns empty/null fields for a junk payload rather than throwing', () => {
    const parsed = parseInboundEmail(null)
    expect(parsed.toAddresses).toEqual([])
    expect(parsed.from).toBeNull()
    expect(parsed.messageId).toBeNull()
    expect(parsed.emailId).toBeNull()
    expect(parsed.inReplyTo).toBeNull()
    expect(parsed.references).toEqual([])
    expect(parsed.html).toBeUndefined()
  })

  it('reads the html body field alongside text when a payload carries both', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      text: 'plain body',
      html: '<p>rich body</p>',
    })
    expect(parsed.text).toBe('plain body')
    expect(parsed.html).toBe('<p>rich body</p>')
  })

  it('reads the html body field when the payload has no plain-text field', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      html: '<p>only html</p>',
    })
    expect(parsed.text).toBeNull()
    expect(parsed.html).toBe('<p>only html</p>')
  })

  it('leaves html undefined when the payload has no html field', () => {
    const parsed = parseInboundEmail({ to: ['x@y.com'], text: 'plain only' })
    expect(parsed.html).toBeUndefined()
  })

  it('reads the threading + auto-mail headers', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      headers: [
        { name: 'In-Reply-To', value: '<a@d>' },
        { name: 'References', value: '<a@d> <b@d>' },
        { name: 'Auto-Submitted', value: 'auto-replied' },
        { name: 'Precedence', value: 'bulk' },
        { name: 'List-Id', value: 'news.example' },
      ],
    })
    expect(parsed.inReplyTo).toBe('a@d')
    expect(parsed.references).toEqual(['a@d', 'b@d'])
    expect(parsed.autoSubmitted).toBe('auto-replied')
    expect(parsed.precedence).toBe('bulk')
    expect(parsed.hasListHeaders).toBe(true)
  })

  it('captures cc recipients (array or string), empty when absent', () => {
    expect(parseInboundEmail({ to: 'x@y.com', cc: ['a@c.com', 'b@c.com'] }).ccAddresses).toEqual([
      'a@c.com',
      'b@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com', cc: 'solo@c.com' }).ccAddresses).toEqual([
      'solo@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com' }).ccAddresses).toEqual([])
  })

  it('leaves attachments undefined when the payload carries none', () => {
    expect(parseInboundEmail({ to: ['x@y.com'], text: 'hi' }).attachments).toBeUndefined()
    expect(parseInboundEmail({ to: ['x@y.com'], attachments: [] }).attachments).toBeUndefined()
  })

  it('maps provider attachment fields (base64 content, snake_case + camelCase)', () => {
    const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
    const pdf = Buffer.from('%PDF-1.4 mock')
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      text: 'see attached',
      attachments: [
        {
          filename: 'logo.png',
          content_type: 'image/png',
          content: png.toString('base64'),
          content_id: '<cid1@host>',
          content_disposition: 'inline',
        },
        { name: 'invoice.pdf', contentType: 'application/pdf', content: pdf.toString('base64') },
        { filename: 'empty.txt', content_type: 'text/plain', content: '' }, // dropped: no bytes
      ],
    })
    expect(parsed.attachments).toHaveLength(2)
    expect(parsed.attachments![0]).toMatchObject({
      filename: 'logo.png',
      contentType: 'image/png',
      contentId: 'cid1@host',
      disposition: 'inline',
    })
    expect(parsed.attachments![0].bytes.equals(png)).toBe(true)
    expect(parsed.attachments![1]).toMatchObject({
      filename: 'invoice.pdf',
      contentType: 'application/pdf',
      contentId: null,
      disposition: 'attachment',
    })
  })
})

describe('parseRawEmail', () => {
  it('parses headers and a plain-text body from a raw RFC822 message', () => {
    const raw = [
      'From: Jane Visitor <jane@example.com>',
      'To: reply+conversation_abc.sig@tenaevexeo.resend.app',
      'Subject: Re: ticket',
      'Message-ID: <m-1@example.com>',
      'In-Reply-To: <c.abc.n1@tenaevexeo.resend.app>',
      'References: <c.abc.n0@tenaevexeo.resend.app> <c.abc.n1@tenaevexeo.resend.app>',
      '',
      'This is my reply.',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc.sig@tenaevexeo.resend.app'])
    expect(parsed.subject).toBe('Re: ticket')
    expect(parsed.messageId).toBe('<m-1@example.com>')
    expect(parsed.inReplyTo).toBe('c.abc.n1@tenaevexeo.resend.app')
    expect(parsed.references).toEqual([
      'c.abc.n0@tenaevexeo.resend.app',
      'c.abc.n1@tenaevexeo.resend.app',
    ])
    expect(parsed.text).toBe('This is my reply.')
    expect(parsed.html).toBeUndefined()
  })

  it('unfolds a folded header (continuation line)', () => {
    const raw = ['Subject: a very long', ' folded subject', '', 'body'].join('\r\n')
    expect(parseRawEmail(raw).subject).toBe('a very long folded subject')
  })

  it('parses Reply-To, which is where our own mail carries the address we minted', () => {
    const raw = [
      'From: Support <noreply@acme.example>',
      'To: Jane <jane@example.com>',
      'Reply-To: Acme Support <ws-t1+cabc.sig@tenaevexeo.resend.app>, ops@acme.example',
      '',
      'body',
    ].join('\r\n')
    expect(parseRawEmail(raw).replyToAddresses).toEqual([
      'Acme Support <ws-t1+cabc.sig@tenaevexeo.resend.app>',
      'ops@acme.example',
    ])
    // Absent is empty, never a one-element list holding nothing: the loop guard
    // asks each entry whether it is an address we minted, and '' is not.
    expect(parseRawEmail(['To: x@y', '', 'body'].join('\r\n')).replyToAddresses).toEqual([])
  })

  it('keeps the TOPMOST Authentication-Results, which is the one our own MTA added', () => {
    // Trace headers are prepended, so the first instance is the last hop: ours.
    // Any further instance was written by an earlier hop or simply typed by the
    // sender, and RFC 8601 §5 says a receiver ignores those. The trust gate
    // (§4.8) turns this value into an attach-or-drop decision, so picking the
    // wrong instance is a stranger choosing whether we treat them as verified.
    const raw = [
      'Authentication-Results: mx.quackback.io; spf=fail smtp.mailfrom=spoof.example;' +
        ' dmarc=fail (p=reject dis=reject) header.from=acme.com',
      'Received: from spoof.example by mx.quackback.io',
      'From: "Chief Executive" <ceo@acme.com>',
      'Subject: wire transfer',
      'Authentication-Results: mx.quackback.io; dmarc=pass header.from=acme.com',
      '',
      'body',
    ].join('\r\n')
    expect(parseRawEmail(raw).authenticationResults).toBe(
      'mx.quackback.io; spf=fail smtp.mailfrom=spoof.example; dmarc=fail (p=reject dis=reject) header.from=acme.com'
    )
  })

  it('parses Cc recipients from the header', () => {
    const raw = [
      'To: support@acme.com',
      'Cc: alice@example.com, Bob <bob@example.com>',
      '',
      'body',
    ].join('\r\n')
    expect(parseRawEmail(raw).ccAddresses).toEqual(['alice@example.com', 'Bob <bob@example.com>'])
  })

  it('decodes a quoted-printable body', () => {
    const raw = [
      'Content-Type: text/plain',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      'Caf=C3=A9 time =\n now',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('Café time  now')
    expect(parsed.html).toBeUndefined()
  })

  it('extracts both text/plain and text/html parts of a multipart/alternative message, one quoted-printable', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/plain',
      '',
      'plain body here',
      '--B',
      'Content-Type: text/html',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      '<p>Caf=C3=A9 html body</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text?.trim()).toBe('plain body here')
    expect(parsed.html?.trim()).toBe('<p>Café html body</p>')
  })

  it('extracts the html part of an HTML-only (non-multipart) message', () => {
    const raw = [
      'Content-Type: text/html; charset=utf-8',
      '',
      '<p>Only an HTML body here.</p>',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html).toBe('<p>Only an HTML body here.</p>')
  })

  it('extracts the html part of a multipart message with no text/plain part', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/html',
      '',
      '<p>html-only alternative</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html?.trim()).toBe('<p>html-only alternative</p>')
  })

  it('leaves attachments undefined for a message that carries no MIME parts', () => {
    const raw = ['Content-Type: text/plain', '', 'just text'].join('\r\n')
    expect(parseRawEmail(raw).attachments).toBeUndefined()
  })

  it('does not overflow on a deeply nested multipart bomb (bounded recursion)', () => {
    // Each level nests a fresh multipart with a distinct boundary so the walk
    // truly recurses (a shared boundary would flatten via body.split). Without
    // a depth bound this overflows the stack; the poller would then retry the
    // message forever. 200 levels is well past the cap.
    const DEPTH = 200
    let raw = ['Content-Type: text/plain', '', 'deep body'].join('\r\n')
    for (let i = DEPTH; i > 0; i--) {
      const b = `B${i}`
      raw = [`Content-Type: multipart/mixed; boundary="${b}"`, '', `--${b}`, raw, `--${b}--`].join(
        '\r\n'
      )
    }
    // The assertion is simply that this returns rather than throwing RangeError.
    expect(() => parseRawEmail(raw)).not.toThrow()
  })
})

describe('parseRawEmail — MIME attachment parts (P4.4)', () => {
  const pngBytes = Buffer.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  ])
  const pdfBytes = Buffer.from('%PDF-1.4\nmock invoice payload\n%%EOF')

  it('walks multipart/mixed(alternative(text,html-cid) + inline image + pdf) and collects both parts', () => {
    const raw = [
      'Content-Type: multipart/mixed; boundary="OUT"',
      '',
      'This is a multipart message in MIME format.',
      '--OUT',
      'Content-Type: multipart/alternative; boundary="ALT"',
      '',
      '--ALT',
      'Content-Type: text/plain',
      '',
      'Here is the logo.',
      '--ALT',
      'Content-Type: text/html',
      '',
      '<div dir="ltr">Here is the logo <img src="cid:logo123@host"></div>',
      '--ALT--',
      '--OUT',
      'Content-Type: image/png',
      'Content-Transfer-Encoding: base64',
      'Content-ID: <logo123@host>',
      'Content-Disposition: inline; filename="logo.png"',
      '',
      pngBytes.toString('base64'),
      '--OUT',
      'Content-Type: application/pdf; name="invoice.pdf"',
      'Content-Transfer-Encoding: base64',
      'Content-Disposition: attachment; filename="invoice.pdf"',
      '',
      pdfBytes.toString('base64'),
      '--OUT--',
    ].join('\r\n')

    const parsed = parseRawEmail(raw)
    expect(parsed.text?.trim()).toBe('Here is the logo.')
    expect(parsed.html).toContain('cid:logo123@host')
    expect(parsed.attachments).toHaveLength(2)

    const [img, pdf] = parsed.attachments!
    expect(img).toMatchObject({
      contentType: 'image/png',
      contentId: 'logo123@host',
      disposition: 'inline',
      filename: 'logo.png',
    })
    expect(img.bytes.equals(pngBytes)).toBe(true)

    expect(pdf).toMatchObject({
      contentType: 'application/pdf',
      contentId: null,
      disposition: 'attachment',
      filename: 'invoice.pdf',
    })
    expect(pdf.bytes.toString('utf8')).toContain('%PDF-1.4')
  })

  it('decodes a quoted-printable attachment part', () => {
    const raw = [
      'Content-Type: multipart/mixed; boundary="M"',
      '',
      '--M',
      'Content-Type: text/plain',
      '',
      'body',
      '--M',
      'Content-Type: text/calendar; name="event.ics"',
      'Content-Transfer-Encoding: quoted-printable',
      'Content-Disposition: attachment; filename="event.ics"',
      '',
      'SUMMARY:Caf=C3=A9',
      '--M--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.attachments).toHaveLength(1)
    expect(parsed.attachments![0].contentType).toBe('text/calendar')
    expect(parsed.attachments![0].bytes.toString('utf8').trim()).toBe('SUMMARY:Café')
  })
})

describe('decodeEncodedWords', () => {
  it('leaves plain ASCII untouched', () => {
    expect(decodeEncodedWords('Re: your question')).toBe('Re: your question')
    expect(decodeEncodedWords(null)).toBeNull()
    expect(decodeEncodedWords('')).toBe('')
  })

  it('decodes a Q-encoded word, treating _ as a space', () => {
    expect(decodeEncodedWords('=?UTF-8?Q?Caf=C3=A9_closed_early?=')).toBe('Café closed early')
  })

  it('decodes a B-encoded (base64) word', () => {
    const encoded = `=?UTF-8?B?${Buffer.from('Grüße aus Köln').toString('base64')}?=`
    expect(decodeEncodedWords(encoded)).toBe('Grüße aus Köln')
  })

  it('joins adjacent encoded-words without inserting the folding whitespace', () => {
    // A long subject is split across words; the space between them is folding,
    // not content, so it must not survive into the decoded string.
    expect(decodeEncodedWords('=?UTF-8?Q?Caf=C3=A9?= =?UTF-8?Q?_closed?=')).toBe('Café closed')
  })

  it('keeps literal whitespace between an encoded word and plain text', () => {
    expect(decodeEncodedWords('Re: =?UTF-8?Q?caf=C3=A9?= today')).toBe('Re: café today')
  })

  it('decodes a non-UTF-8 charset', () => {
    // ISO-8859-1 0xE9 is é — a single byte, unlike its UTF-8 encoding.
    expect(decodeEncodedWords('=?ISO-8859-1?Q?caf=E9?=')).toBe('café')
  })

  it('handles CJK and emoji subjects', () => {
    const jp = `=?UTF-8?B?${Buffer.from('請求について').toString('base64')}?=`
    expect(decodeEncodedWords(jp)).toBe('請求について')
    const emoji = `=?UTF-8?B?${Buffer.from('🚨 outage').toString('base64')}?=`
    expect(decodeEncodedWords(emoji)).toBe('🚨 outage')
  })

  it('keeps the original token when the charset is unknown', () => {
    // A mangled subject is better than a rejected message.
    expect(decodeEncodedWords('=?NOT-A-CHARSET?Q?abc?=')).toBe('=?NOT-A-CHARSET?Q?abc?=')
  })

  it('passes an invalid escape through rather than failing the whole word', () => {
    // `=ZZ` is not valid hex. Emitting the literal characters shows the reader
    // something closer to the intent than the raw `=?...?=` scaffolding would.
    expect(decodeEncodedWords('=?UTF-8?Q?ok_=ZZ?=')).toBe('ok =ZZ')
  })
})

describe('parseRawEmail — RFC 2047 headers', () => {
  it('decodes an encoded subject, sender display name, and attachment filename', () => {
    const raw = [
      'From: =?UTF-8?Q?Bj=C3=B6rn_Andr=C3=A9?= <bjorn@example.com>',
      'To: support@acme.test',
      '=?UTF-8?Q?Subject?=: ignored',
      'Subject: =?UTF-8?Q?Rechnung_f=C3=BCr_M=C3=A4rz?=',
      'Content-Type: multipart/mixed; boundary=b1',
      '',
      '--b1',
      'Content-Type: text/plain',
      '',
      'hallo',
      '--b1',
      'Content-Type: application/pdf; name="=?UTF-8?Q?Rechnung_M=C3=A4rz.pdf?="',
      'Content-Disposition: attachment; filename="=?UTF-8?Q?Rechnung_M=C3=A4rz.pdf?="',
      'Content-Transfer-Encoding: base64',
      '',
      Buffer.from('%PDF-1.4 fake').toString('base64'),
      '--b1--',
      '',
    ].join('\r\n')

    const parsed = parseRawEmail(raw)
    expect(parsed.subject).toBe('Rechnung für März')
    expect(parsed.from).toBe('Björn André <bjorn@example.com>')
    // The address still resolves once the display name is decoded.
    expect(normalizeSenderAddress(parsed.from)).toBe('bjorn@example.com')
    expect(parsed.attachments?.[0].filename).toBe('Rechnung März.pdf')
  })
})

describe('parseMessageIdList', () => {
  it('extracts all angle-bracketed ids, bare and trimmed', () => {
    expect(parseMessageIdList('<a@d>  <b@d>')).toEqual(['a@d', 'b@d'])
  })
  it('falls back to a bare, whitespace-free value', () => {
    expect(parseMessageIdList('bare@d')).toEqual(['bare@d'])
  })
  it('returns [] for null or a value with no usable id', () => {
    expect(parseMessageIdList(null)).toEqual([])
    expect(parseMessageIdList('no ids here')).toEqual([])
  })
})

describe('inboundDedupeKey', () => {
  // No cast. A fixture asserted into the type compiles whatever the type later
  // requires, so the next field the ingest path depends on would be missing here
  // and nothing would say so — which is how a producer ends up feeding the
  // system a message shape the system does not actually accept.
  const parsed = (over: Partial<ParsedInboundEmail>): ParsedInboundEmail => ({
    toAddresses: [],
    ccAddresses: [],
    replyToAddresses: [],
    from: 'someone@example.com',
    subject: null,
    text: '',
    messageId: null,
    emailId: null,
    inReplyTo: null,
    references: [],
    autoSubmitted: null,
    autoResponseSuppress: null,
    precedence: null,
    hasListHeaders: false,
    authenticationResults: null,
    ...over,
  })

  it('is the message’s own id, unchanged and unprefixed', () => {
    // Every row ingested before the fallback existed is filed under this exact
    // value, so re-spelling it would make today's copy of a redelivered message
    // fail to match yesterday's row.
    expect(inboundDedupeKey(parsed({ messageId: '<m-1@example.com>' }))).toBe('<m-1@example.com>')
  })

  it('falls back to the transport id, namespaced, and only when there is no Message-ID', () => {
    expect(inboundDedupeKey(parsed({ transportMessageId: 'ses-1' }))).toBe('qb-transport:ses-1')
    expect(
      inboundDedupeKey(parsed({ messageId: '<m-1@example.com>', transportMessageId: 'ses-1' }))
    ).toBe('<m-1@example.com>')
    expect(inboundDedupeKey(parsed({}))).toBeNull()
    expect(inboundDedupeKey(parsed({ transportMessageId: '   ' }))).toBeNull()
  })

  it('caps BOTH kinds of id, because both land in one index', () => {
    // The cap belongs to the key, not to either source of one. A `Message-ID`
    // arrives in a header nobody upstream bounds; capping only the transport id
    // our own sender sets would leave the exposed one uncapped in the same
    // unique index, where an oversized entry is not a bad dedupe key but an
    // INSERT that throws.
    const atCeiling = `<${'x'.repeat(MAX_DEDUPE_KEY_CHARS - 2)}>`
    expect(atCeiling.length).toBe(MAX_DEDUPE_KEY_CHARS)
    expect(inboundDedupeKey(parsed({ messageId: atCeiling }))).toBe(atCeiling)
    expect(inboundDedupeKey(parsed({ messageId: `${atCeiling}x` }))).toBeNull()

    const transportAtCeiling = 'x'.repeat(MAX_TRANSPORT_MESSAGE_ID_CHARS)
    expect(inboundDedupeKey(parsed({ transportMessageId: transportAtCeiling }))).toHaveLength(
      MAX_DEDUPE_KEY_CHARS
    )
    expect(inboundDedupeKey(parsed({ transportMessageId: `${transportAtCeiling}x` }))).toBeNull()
  })

  it('drops an over-long id rather than truncating it', () => {
    // Truncation would be worse than the throw it avoids: two distinct long ids
    // would truncate to one key, and the second message would be silently
    // suppressed as a duplicate of a message it has nothing to do with.
    const long = (tail: string) => `<${'x'.repeat(MAX_DEDUPE_KEY_CHARS)}${tail}@example.com>`
    expect(inboundDedupeKey(parsed({ messageId: long('a') }))).toBeNull()
    expect(inboundDedupeKey(parsed({ messageId: long('b') }))).toBeNull()
  })
})

describe('messageIdDomain', () => {
  it('reads the domain from an angle-bracketed or bare id', () => {
    expect(messageIdDomain('<x@Mail.Example.com>')).toBe('mail.example.com')
    expect(messageIdDomain('x@d')).toBe('d')
    expect(messageIdDomain(null)).toBeNull()
  })
})

describe('isAutoGeneratedEmail', () => {
  const base: ParsedInboundEmail = {
    toAddresses: [],
    ccAddresses: [],
    replyToAddresses: [],
    from: 'a@b.com',
    subject: null,
    text: 'hi',
    messageId: '<m@sender.example>',
    emailId: null,
    inReplyTo: null,
    references: [],
    autoSubmitted: null,
    autoResponseSuppress: null,
    precedence: null,
    hasListHeaders: false,
    authenticationResults: null,
  }

  it('passes an ordinary human reply', () => {
    expect(isAutoGeneratedEmail(base)).toBe(false)
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'no' })).toBe(false)
  })

  it('drops auto-submitted, suppressed, bulk/junk/list, and list mail', () => {
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'auto-replied' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, autoResponseSuppress: 'All' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'bulk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'junk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'list' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, hasListHeaders: true })).toBe(true)
  })

  it('drops our own mail looping back (Message-ID on one of our domains)', () => {
    const ownDomains = new Set(['sender.example'])
    expect(isAutoGeneratedEmail(base, ownDomains)).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, messageId: '<m@other.example>' }, ownDomains)).toBe(
      false
    )
  })
})

/**
 * Recognising one of our own mails coming back, on a transport that does not let
 * us keep our own `Message-ID`.
 *
 * The old test of authorship was the host on the `Message-ID`: we minted the id,
 * so the host was a domain we operate. A provider that assigns its own id ends
 * that — the host on the wire is the provider's, shared with every other account
 * on the region, and it proves nothing about who sent the message. What is left
 * that we still control is the reply address we put on the mail ourselves: it
 * carries this workspace's label and an HMAC tag over it, so nobody who has not
 * received one of our mails can write one down.
 *
 * The predicate is the REAL one from the address grammar and the fixtures are
 * minted by the REAL minter, so these tests fail if the two sides ever stop
 * agreeing — which a hand-written fake predicate could never notice.
 */
describe('mailLoopSignal', () => {
  const ENV = {
    EMAIL_INBOUND_DOMAIN: 'tenaevexeo.resend.app',
    EMAIL_INBOUND_SIGNING_SECRET: 'whsec_dGVzdHNlY3JldA==',
  }
  const SLUG = 'ws-t1'
  const CONVERSATION_ID = 'conversation_01kw8qxn1eeh4t2rek7varh032' as ConversationId
  /** The addresses this install mints and puts on its own outbound mail. */
  const OUR_REPLY_TO = inboundReplyToAddress(CONVERSATION_ID, SLUG, ENV)!
  /** The domains whose `Message-ID` host we mint ourselves. */
  const OUR_DOMAINS = new Set(['tenaevexeo.resend.app', 'acme.example'])
  /** The question the ingest core asks, wired exactly as it wires it. */
  const ours = (address: string) => isOwnInboundAddress(address, SLUG, ENV)

  /**
   * An id in the shape the sending provider assigns: its own opaque local part
   * at a host shared by every account on the region. Both of our own mail and of
   * every stranger's, which is the whole point.
   */
  const providerId = (local: string) => `<${local}@email.amazonses.com>`

  const message = (over: Partial<ParsedInboundEmail>): ParsedInboundEmail => ({
    toAddresses: [],
    ccAddresses: [],
    replyToAddresses: [],
    from: 'jane@example.com',
    subject: 'Re: your message',
    text: 'hi',
    messageId: null,
    emailId: null,
    inReplyTo: null,
    references: [],
    autoSubmitted: null,
    autoResponseSuppress: null,
    precedence: null,
    hasListHeaders: false,
    authenticationResults: null,
    ...over,
  })

  it('names the reply address when our own mail returns without our Message-ID', () => {
    const ourMailComingBack = message({
      from: 'Support <noreply@acme.example>',
      messageId: providerId('0100019a1f4c8e21-6b2d'),
      toAddresses: ['jane@example.com'],
      replyToAddresses: [OUR_REPLY_TO],
    })
    // WHICH signal, not merely that there was one: this one is an inference
    // about a header the sender controls, and the ingest core retains what it
    // infers and suppresses only what it can prove.
    expect(mailLoopSignal(ourMailComingBack, OUR_DOMAINS, ours)).toBe('own_reply_to')
  })

  it('does not claim a different account’s mail that shares the provider’s Message-ID host', () => {
    // THE decisive case. This message is exactly what "add amazonses.com to the
    // set of hosts that mean ours" would swallow: a real customer writing in,
    // whose own mail happens to leave through the same provider and region as
    // ours, so its Message-ID host is character-for-character the one on our own
    // mail. Nothing about it is ours.
    const strangerViaSameProvider = message({
      from: 'Billing <billing@other-company.example>',
      messageId: providerId('0100019a1f4c8e21-9f04'),
      toAddresses: [OUR_REPLY_TO],
      replyToAddresses: ['billing@other-company.example'],
      text: 'Our invoice did not arrive, can you check?',
    })
    expect(mailLoopSignal(strangerViaSameProvider, OUR_DOMAINS, ours)).toBeNull()
    expect(isAutoGeneratedEmail(strangerViaSameProvider, OUR_DOMAINS)).toBe(false)
  })

  it('does not claim a reply merely for being ADDRESSED to an address we minted', () => {
    // Every genuine reply carries our address — in `To`, because that is where
    // we asked it to be sent. Reading the recipients instead of the reply
    // address would suppress the entire inbound channel, which is why the
    // question is asked of `Reply-To` alone.
    const genuineReply = message({
      from: 'Jane <jane@example.com>',
      messageId: providerId('0100019a1f4c8e21-aa11'),
      toAddresses: [OUR_REPLY_TO],
      ccAddresses: [OUR_REPLY_TO],
      replyToAddresses: [],
    })
    expect(mailLoopSignal(genuineReply, OUR_DOMAINS, ours)).toBeNull()
  })

  it('does not claim a reply whose sender set a Reply-To of their own', () => {
    const replyWithOwnReplyTo = message({
      from: 'Jane <jane@example.com>',
      messageId: '<x@example.com>',
      toAddresses: [OUR_REPLY_TO],
      replyToAddresses: ['Jane at work <jane@work.example>'],
    })
    expect(mailLoopSignal(replyWithOwnReplyTo, OUR_DOMAINS, ours)).toBeNull()
  })

  it('does not accept a Reply-To shaped like ours whose tag was forged', () => {
    const local = OUR_REPLY_TO.slice(0, OUR_REPLY_TO.indexOf('@'))
    const tag = local.slice(local.lastIndexOf('.') + 1)
    const forged = OUR_REPLY_TO.replace(tag, `${tag[0] === 'A' ? 'B' : 'A'}${tag.slice(1)}`)
    // Identical to ours everywhere a shape test can look; only the tag's value
    // differs, so only the HMAC separates them.
    expect(forged).not.toBe(OUR_REPLY_TO)
    expect(forged.length).toBe(OUR_REPLY_TO.length)
    expect(mailLoopSignal(message({ replyToAddresses: [forged] }), OUR_DOMAINS, ours)).toBeNull()
  })

  it('does not accept a neighbouring workspace’s reply address on the same fleet', () => {
    const neighbour = inboundReplyToAddress(CONVERSATION_ID, 'ws-t2', ENV)!
    expect(mailLoopSignal(message({ replyToAddresses: [neighbour] }), OUR_DOMAINS, ours)).toBeNull()
  })

  it('still names the Message-ID on the rung where we mint the id ourselves', () => {
    // SMTP and the console rung both keep the header we set, so the domain test
    // is still the whole answer there. Adding the reply-address signal must not
    // cost a self-hoster the guard they already had — and this signal IS a fact
    // about that install, so it keeps the suppression the other one gives up.
    const smtpLoop = message({
      messageId: '<c.01kw8qxn1eeh4t2rek7varh032.n1@acme.example>',
      replyToAddresses: [],
    })
    expect(mailLoopSignal(smtpLoop, OUR_DOMAINS, ours)).toBe('own_message_id')
    expect(isAutoGeneratedEmail(smtpLoop, OUR_DOMAINS)).toBe(true)
  })

  it('reports the reply address when a message answers both, so it is retained', () => {
    // Order is a disposition, not a preference: this message is refused either
    // way, and reporting the inference is what keeps a copy of it.
    const both = message({
      messageId: '<c.01kw8qxn1eeh4t2rek7varh032.n1@acme.example>',
      replyToAddresses: [OUR_REPLY_TO],
    })
    expect(mailLoopSignal(both, OUR_DOMAINS, ours)).toBe('own_reply_to')
  })

  it('answers "not ours" when the signal is absent, which is the safe direction', () => {
    // Absent means ingested, never refused. Getting this wrong in the other
    // direction costs a customer their message; getting it wrong in this
    // direction files one the other auto-mail guards (RFC 3834, Precedence,
    // List-*) and the dedupe key still stand behind.
    const noSignal = message({
      messageId: providerId('0100019a1f4c8e21-bb22'),
      replyToAddresses: [],
    })
    expect(mailLoopSignal(noSignal, OUR_DOMAINS, ours)).toBeNull()
    // And with no predicate wired at all, our own mail coming back is likewise
    // ingested rather than refused.
    const ourMailComingBack = message({
      messageId: providerId('0100019a1f4c8e21-6b2d'),
      replyToAddresses: [OUR_REPLY_TO],
    })
    expect(mailLoopSignal(ourMailComingBack, OUR_DOMAINS)).toBeNull()
  })
})

describe('extractReplyText', () => {
  it('drops a Gmail-style quoted history below "On … wrote:"', () => {
    const raw = [
      'This is my reply.',
      '',
      'On Mon, Jun 1, 2026 at 9:00 AM Support <reply+x@d> wrote:',
      '> previous agent message',
      '> more quoted text',
    ].join('\n')
    expect(extractReplyText(raw)).toBe('This is my reply.')
  })

  it('drops a leading-`>` quoted block with no separator line', () => {
    const raw = ['My answer is here.', '> quoted', '> quoted 2'].join('\n')
    expect(extractReplyText(raw)).toBe('My answer is here.')
  })

  it('strips a trailing signature after the "-- " delimiter', () => {
    const raw = ['Sounds good.', '', '-- ', 'Jane Visitor', 'Acme Inc'].join('\n')
    expect(extractReplyText(raw)).toBe('Sounds good.')
  })

  it('leaves a plain reply untouched (trimmed)', () => {
    expect(extractReplyText('  just a normal reply  ')).toBe('just a normal reply')
  })

  it('keeps a reply that begins with a "From:" prose line (not a forwarded header)', () => {
    expect(extractReplyText('From: my perspective this is broken\nplease help')).toBe(
      'From: my perspective this is broken\nplease help'
    )
  })

  it('keeps prose that merely contains a mid-body "From:" line', () => {
    const raw = 'I have two questions.\n\nFrom: the docs it says X\nCan you clarify?'
    expect(extractReplyText(raw)).toBe(raw)
  })

  it('falls back to the visitor text when a quote separator lands on the first line', () => {
    // Some clients put the attribution line first; cutting at it would drop the
    // whole message, so we recover the non-quoted text instead of returning "".
    expect(extractReplyText('On Mon, Jun 1, 2026 someone wrote:\nThanks, this is fixed now!')).toBe(
      'Thanks, this is fixed now!'
    )
  })

  it('still returns empty for a reply that is entirely quoted history', () => {
    expect(extractReplyText('On Mon wrote:\n> only quoted text\n> more quoted')).toBe('')
  })
})

describe('extractEmailAddress', () => {
  it('returns a bare address lowercased and trimmed', () => {
    expect(extractEmailAddress(' Jane@Example.COM ')).toBe('jane@example.com')
  })

  it('extracts the addr-spec from a name-addr From header', () => {
    expect(extractEmailAddress('Jane Visitor <Jane@Example.com>')).toBe('jane@example.com')
  })

  it('handles a quoted display name containing a comma', () => {
    expect(extractEmailAddress('"Doe, Jane" <jane@example.com>')).toBe('jane@example.com')
  })

  it('returns null for null, empty, or address-less input', () => {
    expect(extractEmailAddress(null)).toBeNull()
    expect(extractEmailAddress('')).toBeNull()
    expect(extractEmailAddress('not an address')).toBeNull()
  })

  it('returns null for malformed addr-specs', () => {
    expect(extractEmailAddress('Jane <@example.com>')).toBeNull()
    expect(extractEmailAddress('Jane <jane@>')).toBeNull()
    expect(extractEmailAddress('a@b@c')).toBeNull()
  })
})
